# Generated by Django 3.2.3 on 2021-05-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210513_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
