# Generated by Django 3.2.3 on 2021-05-17 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order_date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
